# Generated by Django 3.2.8 on 2021-11-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
