# Generated by Django 3.2.8 on 2021-11-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0002_alter_products_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
