# Generated by Django 3.2.9 on 2021-11-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0009_auto_20211111_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
