# Generated by Django 3.2.7 on 2021-11-17 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0010_auto_20211112_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.AlterModelOptions(
            name='laptops',
            options={'managed': False},
        ),
        migrations.RenameField(
            model_name='buyermodel',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='sellermodel',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='buyermodel',
            name='mobile_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='mobile_number',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='sellermodel',
            table='seller',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techeria_app.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techeria_app.products')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='techeria_app.buyermodel'),
        ),
    ]
