# Generated by Django 3.2.7 on 2021-11-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0011_auto_20211117_0625'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='laptops',
            table='laptops',
        ),
    ]
