# Generated by Django 3.2.7 on 2021-11-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0011_order_orderitem'),
        ('techeria_app', '0012_alter_laptops_table'),
    ]

    operations = [
    ]
