# Generated by Django 3.2.7 on 2021-11-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0013_merge_0011_order_orderitem_0012_alter_laptops_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'smartphone',
            },
        ),
        migrations.AlterModelOptions(
            name='laptops',
            options={},
        ),
        migrations.RenameField(
            model_name='buyermodel',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='sellermodel',
            old_name='username',
            new_name='user_name',
        ),
    ]
