# Generated by Django 3.2.7 on 2021-11-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0014_auto_20211130_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyermodel',
            name='mobile_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='mobile_number',
            field=models.CharField(max_length=255),
        ),
    ]
