# Generated by Django 3.2.7 on 2021-11-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0014_auto_20211123_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
