# Generated by Django 3.2.7 on 2021-11-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0015_alter_laptops_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
