# Generated by Django 3.2.7 on 2021-12-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0016_myproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
