# Generated by Django 3.2.7 on 2021-11-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0017_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customUser',
        ),
    ]
