# Generated by Django 3.2.7 on 2021-11-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0019_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
