# Generated by Django 3.2.7 on 2021-11-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0020_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerModel',
        ),
        migrations.DeleteModel(
            name='SellerModel',
        ),
    ]
