# Generated by Django 3.2.8 on 2021-12-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0016_auto_20211201_2224'),
        ('techeria_app', '0021_alter_products_category'),
    ]

    operations = [
    ]
