# Generated by Django 3.2.8 on 2021-12-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0022_merge_20211202_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'accessorie',
            },
        ),
        migrations.DeleteModel(
            name='MyProducts',
        ),
    ]
